/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { ITodoData } from './todo.data';
import { ITodoProps } from './todo.props.autogenerated';

export interface ITodoViewProps extends ITodoProps<ITodoData> {}

/**
 *
 * Todo component
 * @extends {React.PureComponent<ITodoProps<ITodoData>>}
 */
class Todo extends React.PureComponent<ITodoProps<ITodoData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default Todo;
