/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';
import { AsyncResult } from '@msdyn365-commerce/retail-proxy';

import Todo from '../todo';
import { ITodoData } from '../todo.data';
import { ITodoConfig, ITodoProps } from '../todo.props.autogenerated';
import { Card } from '../../../types';

const mockedCards: Card[] = [];
const mockedCard: Card = { id: '0', title: 'title', text: 'text', src: 'src' };

// @ts-ignore
const getCards: AsyncResult<{ cards: Card[] }> = {
    result: { cards: mockedCards }
};

// @ts-ignore
const postCard: AsyncResult<{ card: Card }> = {
    result: { card: mockedCard }
};

const mockData: ITodoData = {
    actionResponse: {
        text: 'Sample Response Data'
    },
    getCards,
    postCard
};

const mockConfig: ITodoConfig = {
    showText: 'todo'
};

const mockActions = {};

describe('Todo', () => {
    let moduleProps: ITodoProps<ITodoData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ITodoProps<ITodoData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<Todo {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
